#logging:
#  path: e:/mylog    #添加日志

mybatis:
  configuration:
    map-underscore-to-camel-case: true #版本不同，对应的配置项可能不同
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/xbhy?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
    password: root
  application:
    name: solr
    data:
      solr:
        host: http://localhost:8983/solr/collection1
#      mongodb:
#        host: 192.168.137.130
#        database: xbhy

  redis:
    password: 123456
  cache:
    type: redis

