spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/xbhy?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
    password: root
  redis:
    password: 123456
  cache:
    type: redis
